Repository optuna/optuna-dashboard, pull requests merged in 2023-10, with the labels that each got.

#642 Video playback on ArtifactCardMedia
  optuna_dashboard/ts/components/ArtifactCardMedia.tsx
Labels: sprint-20230930

#646 Add experimental warnings on doc
  optuna_dashboard/preferential/_study.py
Labels: documentation

#647 Make `PreferentialGPSampler` the default for preferential optimization
  optuna_dashboard/preferential/_study.py
  python_tests/preferential/test_study.py
  python_tests/test_api.py
  python_tests/test_preferential_history.py
  python_tests/test_serializers.py
Labels: enhancement

#643 Return Result from wasm_fanova_calculate
  rustlib/src/lib.rs
  standalone_app/src/components/PlotImportance.tsx
Labels: sprint-20230930
