Repository optuna/optuna-dashboard, pull requests merged in 2023-11, with the labels that each got.

#688 Support constraints in slice plot
  optuna_dashboard/ts/components/GraphSlice.tsx
Labels: enhancement

#697 Fix audio artifact component
  optuna_dashboard/ts/components/ArtifactCardMedia.tsx
Labels: bug

#709 Add codecov badge
  README.md
Labels: documentation
